import NavbarComp from "@/components/Navbar";
import "./globals.scss";

export const metadata = {
  title: "Eamin Khan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Yuji+Syuku&display=swap"
        />
      </head>
      <body>
        <NavbarComp />
        {children}
      </body>
    </html>
  );
}
